export const report =   [
    {
      no: 1,
      reportid: "RPT-001",
      reportedBy: "Alice Johnson",
      contentType: "Post",
      reason: "Inappropriate content",
      status: "Pending",
    },
    {
      no: 2,
      reportid: "RPT-002",
      reportedBy: "Grace Lee",
      contentType: "Profile",
      reason: "Fake profile",
      status: "Banned",
    },
    {
      no: 3,
      reportid: "RPT-003",
      reportedBy: "Eve Adams",
      contentType: "Post",
      reason: "Spam",
      status: "Pending",
    },
    {
      no: 4,
      reportid: "RPT-004",
      reportedBy: "Mia Wong",
      contentType: "Profile",
      reason: "Impersonation",
      status: "Pending",
    },
    {
      no: 5,
      reportid: "RPT-005",
      reportedBy: "Leo Thomas",
      contentType: "Post",
      reason: "Scam",
      status: "Banned",
    },
    {
      no: 6,
      reportid: "RPT-006",
      reportedBy: "Henry Ford",
      contentType: "Post",
      reason: "False information",
      status: "Pending",
    },
    {
      no: 7,
      reportid: "RPT-007",
      reportedBy: "Olivia Stone",
      contentType: "Post",
      reason: "Misinformation",
      status: "Banned",
    },
    {
      no: 8,
      reportid: "RPT-003s",
      reportedBy: "Eve Adams",
      contentType: "Post",
      reason: "Spam",
      status: "Pending",
    },
    {
      no: 9,
      reportid: "RPT-004dsfsd",
      reportedBy: "Mia Wong",
      contentType: "Profile",
      reason: "Impersonation",
      status: "Pending",
    },
    {
      no: 10,
      reportid: "RPT-dsfsd005",
      reportedBy: "Leo Thomas",
      contentType: "Post",
      reason: "Scam",
      status: "Banned",
    },
    {
      no: 11,
      reportid: "RPT-00fsd6",
      reportedBy: "Henry Ford",
      contentType: "Post",
      reason: "False information",
      status: "Pending",
    },
    {
      no: 12,
      reportid: "RPT-0sdf07",
      reportedBy: "Olivia Stone",
      contentType: "Post",
      reason: "Misinformation",
      status: "Banned",
    },
  ]